### ISSUE TITLE
Please add the DueDate parameter to create an issue or update it. 

### ISSUE THREAD

**Issue by pillarion** [nixys/nxs-go-redmine#3]
The API supports it, but this is not reflected in the documentation.

**Comment by borisershov** [comment]
Hi! Added start and due date for create and update issues. Changes available in version `v4.2.0`

Note that `StartDate` and `DueDate` for `IssueUpdateObject` is a pointers for string! So you may do a following actions:
- Set a new value: must be a defined string value (in `YYYY-MM-DD` date format)
- Delete value: must be a defined empty string
- Leave unchanged: do not fill this fields with any values

**Comment by pillarion** [comment]
Thank you very much!
