### ISSUE TITLE
Please add support for the Redmine Wiki API

### ISSUE THREAD

**Issue by pillarion** [nixys/nxs-go-redmine#8]
I would really appreciate it if you could add support for the Wiki API. This would significantly automate my page management processes.

**Comment by borisershov** [comment]
Hi! You request is released in [v4.5.0](https://github.com/nixys/nxs-go-redmine/tree/6f2c8757ee4f8b81458e1c7eee8482cd0d3ca5fb) in accordance with [Redmine Wiki documentation](https://www.redmine.org/projects/redmine/wiki/Rest_WikiPages).

Now you able to use Redmine Wiki to automate your processes 👍🤝

**Comment by pillarion** [comment]
that's great news! Thank you so much!

**Comment by pillarion** [comment]
Hi, thanks again for the update. I have a question. Does the API support specifying a parent page when creating/modifying a wiki page?

**Comment by borisershov** [comment]
Hi! Unfortunately no, I checked this moment in the Redmine code. It sounds like a "feature request" to the Redmine developers...  🤔

**Comment by pillarion** [comment]
Thank you! I have added the feature request to the project.

**Comment by borisershov** [comment]
I'll watch for your [issue](https://www.redmine.org/issues/39030) on redmine.org
